-- Create playlist table for fallback videos
create table public.playlist (
  id bigint generated by default as identity primary key,
  video_id text not null,
  title text not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.playlist enable row level security;

-- Policies

-- Public (Anonymous) can view active playlist items
create policy "Public can view active playlist items"
  on public.playlist for select
  using (is_active = true);

-- Authenticated users (Admin in this simple context) can do everything
create policy "Authenticated users can manage playlist"
  on public.playlist for all
  using (auth.role() = 'authenticated');

-- Insert some default mood videos
insert into public.playlist (video_id, title) values 
('jfKp-sQkuxY', 'Lofi Girl - Relax/Study'),
('5qap5aO4i9A', 'Lofi Hip Hop Radio'), 
('w2t5PdoNMnw', 'Trap Mix 2024');
