-- Create table for Influencer Leads
create table if not exists public.influencer_leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  instagram text not null,
  whatsapp text not null,
  status text default 'pending'
);

-- Enable RLS
alter table public.influencer_leads enable row level security;

-- Policies
create policy "Enable insert for everyone"
on public.influencer_leads
for insert
to public
with check (true);

create policy "Enable select for service role only"
on public.influencer_leads
for select
to service_role
using (true);
