-- Add stream_url to events if it doesn't exist
alter table public.events add column if not exists stream_url text;

-- Create playlist table if it doesn't exist
create table if not exists public.playlist (
  id bigint generated by default as identity primary key,
  video_id text not null,
  title text not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on playlist
alter table public.playlist enable row level security;

-- Policies for playlist (Drop first to ensure idempotency)

drop policy if exists "Public can view active playlist items" on public.playlist;
create policy "Public can view active playlist items"
  on public.playlist for select
  using (is_active = true);

drop policy if exists "Admins can view all playlist items" on public.playlist;
create policy "Admins can view all playlist items"
  on public.playlist for select
  using (auth.role() = 'authenticated');

drop policy if exists "Admins can insert playlist items" on public.playlist;
create policy "Admins can insert playlist items"
  on public.playlist for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "Admins can update playlist items" on public.playlist;
create policy "Admins can update playlist items"
  on public.playlist for update
  using (auth.role() = 'authenticated');

drop policy if exists "Admins can delete playlist items" on public.playlist;
create policy "Admins can delete playlist items"
  on public.playlist for delete
  using (auth.role() = 'authenticated');

-- Insert some default mood videos if table is empty
insert into public.playlist (video_id, title)
select 'jfKp-sQkuxY', 'Lofi Girl - Relax/Study'
where not exists (select 1 from public.playlist);

insert into public.playlist (video_id, title)
select '5qap5aO4i9A', 'Lofi Hip Hop Radio'
where not exists (select 1 from public.playlist where video_id = '5qap5aO4i9A');

insert into public.playlist (video_id, title)
select 'w2t5PdoNMnw', 'Trap Mix 2024'
where not exists (select 1 from public.playlist where video_id = 'w2t5PdoNMnw');
