-- Create a table to control the live stream configuration
create table public.stream_config (
  id bigint generated by default as identity primary key,
  video_id text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_by uuid references auth.users(id)
);

-- Turn on Realtime for this table
alter publication supabase_realtime add table public.stream_config;

-- Enable Row Level Security
alter table public.stream_config enable row level security;

-- Policies

-- Everyone can view the stream config (public/anonymous included)
create policy "Stream config is viewable by everyone"
  on public.stream_config for select
  using (true);

-- Only authenticated users can update (For simplicity. Ideally, restrict to Admins)
create policy "Authenticated users can update stream config"
  on public.stream_config for update
  using (auth.role() = 'authenticated');

-- Insert the default row (ID 1)
insert into public.stream_config (video_id)
values ('w2t5PdoNMnw'); -- Default to current live
